FROM python:3.9-slim AS backend

WORKDIR /app

# Install backend dependencies
COPY securefiles/requirements.txt ./
RUN pip3 install -r requirements.txt

# Copy backend source files
COPY securefiles/ .

EXPOSE 8000
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]