FROM node:22.9.0-alpine AS frontend

WORKDIR /app

# Copy frontend source files
COPY securefiles-frontend/package.json securefiles-frontend/package-lock.json ./
RUN yarn add redux react-redux redux-thunk axios web-vitals
RUN yarn add @mui/material @emotion/react @emotion/styled
RUN yarn add @mui/icons-material


COPY securefiles-frontend/ ./

#RUN npm start
CMD ["npm", "start"]
